### ISSUE TITLE
Investigate: using req.headers['x-forwarded-host']

### ISSUE THREAD

**Issue by jekrb** [jekrb/next-absolute-url#1]
Opening this issue so I don't forget.  It might be a good idea to use `req.headers['x-forwarded-host']` as `now dev` serves local lambda functions from a different port.

Original discussion: https://spectrum.chat/zeit/general/an-unexpected-error-has-occurred-serverless-next-js~270a120a-5c88-47e0-b7d9-a4ddf4611886

![image](https://user-images.githubusercontent.com/2081699/57576465-39e2e700-742e-11e9-8364-7e6ae976159e.png)

**Comment by relferreira** [comment]
Hi @jekrb, opened the PR #2 with this modification
